# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vehicle_data_pb2 as vehicle__data__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vehicle_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehicleDataStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVehicleData = channel.stream_unary(
                '/vehicle.VehicleDataStreamer/StreamVehicleData',
                request_serializer=vehicle__data__pb2.VehicleData.SerializeToString,
                response_deserializer=vehicle__data__pb2.StreamResponse.FromString,
                _registered_method=True)


class VehicleDataStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamVehicleData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleDataStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVehicleData': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamVehicleData,
                    request_deserializer=vehicle__data__pb2.VehicleData.FromString,
                    response_serializer=vehicle__data__pb2.StreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicle.VehicleDataStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehicle.VehicleDataStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleDataStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamVehicleData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/vehicle.VehicleDataStreamer/StreamVehicleData',
            vehicle__data__pb2.VehicleData.SerializeToString,
            vehicle__data__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
